### ISSUE TITLE
Mutex in Windows

### ISSUE THREAD

**Issue by gekomad** [akhin/benchmarks#1]
Your code 'atomic_vs_mutex.cpp' in Windows took these times:

$ ptime atomic_vs_mutex.exe atomic
1000000
Execution time: 2.643 s

$ ptime atomic_vs_mutex.exe mutex
1000000
Execution time: 42.861 s

I suggest you change your code in:

```
#include "Mutex.h"
struct MutexCounter {
    Mutex mutex; // *** Wrapper to mutex ***
    long value;
    void increment() {
        mutex.lock();
        //std::lock_guard<std::mutex> guard(mutex);
        value++;
        mutex.unlock();
    }
    void decrement() {
        mutex.lock();
        //std::lock_guard<std::mutex> guard(mutex);
        value--;
        mutex.unlock();
    }
    MutexCounter() : value(0) { }
};
```

get Mutex.h from https://gist.github.com/gekomad/267b884dac64d4a4e68d

 the new time is:

$ ptime atomic_vs_mutex.exe mutex
1000000
Execution time: 2.635 s

this because Conditional Section is more faster than Mutex

**Comment by akhin** [comment]
Hi ,

To be honest, I always thought MSVC`s std::mutex implementation would be a wrapper around CriticalSection therefore I`d expect close results performance wise , but focusing on Linux side , never measured or debugged it , thanks a lot for sharing this.

Sounds like MSVC implementation might even depend on its version : http://stackoverflow.com/questions/9997473/stdmutex-performance-compared-to-win32-critical-section

**Comment by gekomad** [comment]
I don't know MSVC, my test is on gcc (mingw)  :)
In your test suite could include spinlock..

**Comment by akhin** [comment]
Thanks ,updated the code & also the blog post 
https://nativecoding.wordpress.com/2015/02/15/transition-to-c11-the-most-important-features/
